### PR TITLE
Support zip+6 for the us region

### PR DESCRIPTION
**Pull request by dimroc**
This is becoming increasingly prevalent as seen here:
http://www.chiefmarketer.com/zip4-2-zip6/

### CODE REVIEW

**Comment by dgilperez** [comment]
Hmm I can't seem to find any more references on this. It's not working from [USPS](https://tools.usps.com/go/ZipLookupAction!input.action)'s site, nor on [Wikipedia](https://en.wikipedia.org/wiki/ZIP_code) ... I'm not living on the US so I don't have an opinion. Can you provide extra references on this?

**Comment by dimroc** [comment]
We encountered this issue because [easypost.com](www.easypost.com) started returning the zip+4+2 format to us. Below is a quote from wikipedia:

> Customers who send bulk mail can get a discount on postage if they have printed the barcode themselves. This requires more than just a simple font; mailing lists must be standardized with up-to-date Coding Accuracy Support System (CASS)-certified software that adds and verifies a full, correct ZIP+4 code and an additional two digits representing the exact delivery point.

I found some more references here:
http://www.answers.com/Q/How_many_number_are_in_a_ZIP_code
https://en.wikipedia.org/wiki/ZIP_code#Postal_bar_code

**Comment by dimroc** [comment]
Hey JT, Hope you're enjoying the Colorado 🌄 
Considering that the regex supports it, probably so. But that wasn't present for the zip+4 scenario, which is what I used to reference the zip+6 case.

**Comment by dgilperez** [comment]
Thanks for the references! I'm merging this and adding those extra test cases.

**Pull request merged**
