### PR TITLE
Update Mongolia Validator Regexp

### PR DESCRIPTION
**Pull request by lucasfcunha**
Hi,

We use this gem to validate ZipCodes and we had a customer complaining of not being able to create an account with a Mongolia zip code.

Postal Codes on the CLDR were [deprecated as of CLDR 28](https://unicode-org.atlassian.net/browse/CLDR-8791#comment:1)

However, taking a look at some other places ([1](https://www.grcdi.nl/gsb/mongolia.html#H8D85D5C926D174F4391D4E7A388527399597C7E7037A2AA2AMongoliaA20A2DA20A5BA5BPostalA20codesA5DA5DA2AA2A00100400F01201501801B02402C02F032035) and [2](https://en.youbianku.com/mongolia)) I could find that instead of 6 digits the postal code for Mongolia should be 5 digits.

It's possible to have 4 more digits for a delivery point. However, a regular postal code consists of 5 digits.

### CODE REVIEW

**Comment by dgilperez** [comment]
Hey @lucasfcunha thanks for the PR!

You're right, CLDR was the starting point for this effort, but since they deprecated that support I've been updating the regexes (both errors such as this, apparently, and evolutions - yes, postal codes evolve!) from PRs such as yours :) 

Reading that link, I see there is actually another case we should probably support: 

```
99999
99999[-]9999
```

So the regex should be something such as `/\A\d{5}(-?\d{4})?\z/` (untested). 

Would you please update the PR with that?

**Comment by lucasfcunha** [comment]
Hi @dgilperez 

Updated with the suggested changes.

**Review by dgilperez — APPROVED** [review]
Lgtm!

**Comment by dgilperez** [comment]
Thanks @lucasfcunha I will release a new version shortly

🍻

**Pull request merged**
